Repository spatialos/online-services, pull requests merged in 2019-08, with the labels that each got.

#40 Analytics CI
  .buildkite/premerge.steps.yaml
  ci/analytics-endpoint.sh
  services/csharp/IntegrationTest/docker_compose.yml
  services/docker/docker_compose_local_analytics.yml
  services/docker/docker_compose_local_services.yml
Labels: pinned

#76 Rename solution file
  services/csharp/online-services.sln
Labels: jira/no-ticket, size/XS

#78 Add end-of-file newline to editorconfig
  services/csharp/.editorconfig
  services/csharp/DeploymentPool/DeploymentPool.cs
  services/csharp/DeploymentPool/HumanNamer.cs
  services/csharp/DeploymentPool/Reporter.cs
  services/csharp/Gateway.Test/OperationsServiceCancelOperationShould.cs
  services/csharp/Gateway.Test/OperationsServiceListOperationsShould.cs
  services/csharp/Gateway.Test/Util.cs
  services/csharp/GatewayInternal.Test/Util.cs
  services/csharp/IntegrationTest.Matcher/Program.cs
  services/csharp/IntegrationTest/GatewayPerformanceShould.cs
  services/csharp/MemoryStore.Test/Util.cs
  services/csharp/MemoryStore/EntryAlreadyExistsException.cs
  services/csharp/MemoryStore/EntryNotFoundException.cs
  services/csharp/MemoryStore/IMemoryStoreClientManager.cs
  services/csharp/MemoryStore/InsufficientEntriesException.cs
  services/csharp/MemoryStore/MemoryStoreException.cs
  services/csharp/MemoryStore/Redis/RedisClientManager.cs
  services/csharp/MemoryStore/TransactionAbortedException.cs
  services/csharp/Party.Test/GetPartyByPlayerIdShould.cs
  services/csharp/Party.Test/Util.cs
Labels: jira/no-ticket, size/S

#77 Analytics unit tests
  services/csharp/Party.Test/AnalyticsConstants.cs
  services/csharp/Party.Test/CreateInviteShould.cs
  services/csharp/Party.Test/CreatePartyShould.cs
  services/csharp/Party.Test/DeleteInviteShould.cs
  services/csharp/Party.Test/DeletePartyShould.cs
  services/csharp/Party.Test/JoinPartyShould.cs
  services/csharp/Party.Test/KickOutPlayerShould.cs
  services/csharp/Party.Test/LeavePartyShould.cs
  services/csharp/Party.Test/UpdatePartyShould.cs
Labels: jira/no-ticket, size/L

#79 removed pycrypto vulnerability & tweaked endpoint spec context
  services/python/analytics-pipeline/src/requirements/endpoint.txt
  services/terraform/module-analytics/spec/analytics-endpoint.yml
Labels: jira/no-ticket, size/XS

#80 moved to scaler-v2
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#81 changed google_ip to k8s_lb & swapped to newer endpoints container
  services/k8s/analytics-endpoint/deployment.yaml
  services/k8s/analytics-endpoint/service.yaml
  services/terraform/module-analytics/endpoints.tf
  services/terraform/module-analytics/ip.tf
  services/terraform/module-analytics/loadbalancer.tf
  services/terraform/modules.tf
Labels: jira/no-ticket, size/M

#82 updated DNS configuration
  services/k8s/analytics-endpoint/deployment.yaml
Labels: jira/no-ticket, size/XS

#83 reverted to original analytics IP method
  services/k8s/analytics-endpoint/service.yaml
  services/terraform/module-analytics/endpoints.tf
  services/terraform/module-analytics/ip.tf
  services/terraform/module-analytics/loadbalancer.tf
  services/terraform/modules.tf
Labels: jira/no-ticket, size/M
