Repository spatialos/online-services, pull requests merged in 2019-12, with the labels that each got.

#136 Adopt k8s affinity fix from NWX
  services/k8s/analytics-endpoint/deployment.yaml
Labels: jira/no-ticket, size/XS

#137 updated terraform syntax in line with 0.12 to avoid warnings
  services/terraform/gke.tf
  services/terraform/module-analytics/bigquery.tf
  services/terraform/module-analytics/cloud-function.tf
  services/terraform/module-analytics/endpoints.tf
  services/terraform/module-analytics/pubsub.tf
  services/terraform/module-analytics/service-accounts-dataflow.tf
  services/terraform/module-analytics/service-accounts-endpoint.tf
  services/terraform/module-gateway/endpoints.tf
  services/terraform/module-gateway/ip.tf
  services/terraform/module-gateway/memorystore.tf
  services/terraform/module-playfab-auth/endpoints.tf
  services/terraform/module-playfab-auth/ip.tf
  services/terraform/modules.tf
  services/terraform/providers.tf
  services/terraform/services.tf
Labels: jira/no-ticket, size/L

#138 restricted SA GCS access to read/write
  services/terraform/module-analytics/service-accounts-endpoint.tf
  services/terraform/module-analytics/service-accounts-function.tf
Labels: jira/no-ticket, size/S

#139 optimized cloud function to be able to use smallest template
  services/python/analytics-pipeline/src/dataflow/common/functions.py
  services/python/analytics-pipeline/src/function/main.py
  services/terraform/module-analytics/cloud-function.tf
Labels: jira/no-ticket, size/L

#140 updated endpoint string formatting style
  services/python/analytics-pipeline/src/endpoint/main.py
Labels: jira/no-ticket, size/S

#141 Endpoint playfab support
  services/python/analytics-pipeline/src/endpoint/common/functions.py
  services/python/analytics-pipeline/src/endpoint/main.py
Labels: jira/no-ticket, size/M

#142 Function playfab support
  .gitignore
  services/python/analytics-pipeline/src/dataflow/common/bigquery_schema.py
  services/python/analytics-pipeline/src/functions/general/main.py
  services/python/analytics-pipeline/src/functions/playfab/main.py
  services/terraform/module-analytics/archive.tf
  services/terraform/module-analytics/bigquery.tf
  services/terraform/module-analytics/cloud-function.tf
  services/terraform/module-analytics/pubsub.tf
Labels: jira/no-ticket, size/XL

#143 Tweak analytics docs slightly for Windows compatibility
  docs/content/services-packages/analytics-pipeline/backfill.md
  docs/content/services-packages/analytics-pipeline/deploy.md
  docs/content/services-packages/deployment-pool/deploy.md
Labels: jira/no-ticket, size/XS

#144 Change analytics.environment to event.environment, add event.schema
  docs/content/services-packages/deployment-pool/deploy.md
  services/csharp/Common.Test/AnalyticsShould.cs
  services/csharp/Common/Analytics/AnalyicsSenderBuilder.cs
  services/csharp/Common/Analytics/AnalyticsCommandLineArgs.cs
  services/csharp/Common/Analytics/AnalyticsSender.cs
  services/csharp/Common/Analytics/IAnalyticsCommandLineArgs.cs
  services/csharp/DeploymentPool/Program.cs
  services/csharp/Gateway/Program.cs
  services/csharp/GatewayInternal/Program.cs
  services/csharp/Party/PartyServerCommandLineArgs.cs
  services/csharp/PlayFabAuth/Program.cs
  services/csharp/SampleMatcher/Program.cs
  services/docker/docker_compose_local_gateway.yml
  services/k8s/deployment-pool/deployment.yaml
  services/k8s/gateway-internal/deployment.yaml
  services/k8s/gateway/deployment.yaml
  services/k8s/party/deployment.yaml
  services/k8s/playfab-auth/deployment.yaml
  services/k8s/sample-matcher/deployment.yaml
Labels: jira/no-ticket, size/M
