Repository spatialos/online-services, pull requests merged in 2019-10, with the labels that each got.

#112 Update Party phase to Forming when PartyJoinRequest is cancelled
  services/csharp/Gateway.Test/OperationsServiceDeleteOperationShould.cs
  services/csharp/Gateway/OperationsServiceImpl.cs
  services/csharp/IntegrationTest/MatchmakingSystemShould.cs
Labels: jira/no-ticket, size/M

#113 Use unique docker network per build
  ci/build.sh
  services/csharp/IntegrationTest/docker_compose.yml
Labels: jira/no-ticket, size/S

#114 PlayFab ID's can be alphanumeric
  docs/content/get-started/quickstart-4.md
Labels: jira/no-ticket, size/XS

#115 Regenerate proto descriptors with new grpc.tools version
  services/terraform/api_descriptors/gateway_descriptor.pb
  services/terraform/api_descriptors/party_descriptor.pb
  services/terraform/api_descriptors/playfab_auth_descriptor.pb
Labels: jira/no-ticket, size/XS

#116 Regenerate gRPC descriptors with imports included
  services/terraform/api_descriptors/gateway_descriptor.pb
  services/terraform/api_descriptors/party_descriptor.pb
  services/terraform/api_descriptors/playfab_auth_descriptor.pb
Labels: jira/no-ticket, size/XS

#118 Disallow expired cached PIT
  services/csharp/Common/Interceptors/PlayerIdentityTokenValidatingInterceptor.cs
Labels: jira/no-ticket, size/XS

#117 updated docker_componse.yml
  services/csharp/IntegrationTest/docker_compose.yml
Labels: jira/no-ticket, size/S

#121 split build, unit and integration tests into separate CI steps
  .buildkite/premerge.steps.yaml
  ci/build.sh
  ci/integration-tests.sh
  ci/unit-tests.sh
Labels: jira/no-ticket, size/S

#122 Update builder queue
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#123 Fix build warnings in integration test
  services/csharp/IntegrationTest/GatewayPerformanceShould.cs
Labels: jira/no-ticket, size/S

#124 Update builder queue to support Kubernetes tests
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#126 Update esp containers' versions to 1.38.0
  services/docker/docker_compose_local.yml
  services/k8s/gateway/deployment.yaml
  services/k8s/party/deployment.yaml
  services/k8s/playfab-auth/deployment.yaml
Labels: jira/no-ticket, size/XS

#128 Give service accounts package read permissions by default.
  tools/ServiceAccountCLI/Program.cs
  tools/ServiceAccountCLI/README.md
Labels: jira/no-ticket, size/S

#130 Upgrade Platform SDK to 14.2.0
  services/csharp/Base.Matcher/Base.Matcher.csproj
  services/csharp/Base.Matcher/Matcher.cs
  services/csharp/Common/Common.csproj
  services/csharp/Common/Common.nuspec
  services/csharp/DeploymentMetadata.Test/DeploymentMetadata.Test.csproj
  services/csharp/DeploymentPool.Test/DeploymentPool.Test.csproj
  services/csharp/DeploymentPool.Test/DeploymentPoolShould.cs
  services/csharp/DeploymentPool/DeploymentAction.cs
  services/csharp/DeploymentPool/DeploymentPool.cs
  services/csharp/DeploymentPool/DeploymentPool.csproj
  services/csharp/DeploymentPool/PlatformInvoker.cs
  services/csharp/DeploymentPool/Program.cs
  services/csharp/IntegrationTest.Matcher/Matcher.cs
  services/csharp/IntegrationTest/IntegrationTest.csproj
  services/csharp/IntegrationTest/PlayFabAuthShould.cs
  services/csharp/SampleMatcher/PoolMatcher.cs
  services/csharp/SampleMatcher/StandaloneMatcher.cs
Labels: jira/no-ticket, size/L

#119 Consolidate Gateway Operations service into main service
  services/csharp/Gateway.Test/GatewayServiceCancelJoinShould.cs
  services/csharp/Gateway.Test/GatewayServiceGetJoinStatusShould.cs
  services/csharp/Gateway.Test/GatewayServiceJoinShould.cs
  services/csharp/Gateway.Test/OperationsServiceCancelOperationShould.cs
  services/csharp/Gateway.Test/OperationsServiceListOperationsShould.cs
  services/csharp/Gateway/GatewayServiceImpl.cs
  services/csharp/Gateway/OperationsServiceImpl.cs
  services/csharp/Gateway/Program.cs
  services/csharp/Gateway/Reporter.cs
  services/csharp/IntegrationTest/GatewayPerformanceShould.cs
  services/csharp/IntegrationTest/IntegrationTest.csproj
  services/csharp/IntegrationTest/MatchmakingSystemShould.cs
  services/csharp/Proto/Proto.csproj
  services/csharp/Proto/generated/Gateway.cs
  services/csharp/Proto/generated/GatewayGrpc.cs
  services/csharp/SampleClient/Program.cs
  services/proto/gateway/gateway.proto
  services/proto/google/longrunning/operations.proto
  services/proto/google/protobuf/any.proto
  services/proto/google/protobuf/empty.proto
  services/proto/google/rpc/status.proto
  services/terraform/api_descriptors/gateway_descriptor.pb
  services/terraform/spec/gateway_spec.yml
Labels: jira/no-ticket, pinned, size/XXL

#131 Instrument CancelJoin RPC
  services/csharp/Gateway/GatewayServiceImpl.cs
Labels: jira/no-ticket, size/S

#132 Bump version number to 0.2.0
  services/csharp/Base.Matcher/Base.Matcher.csproj
  services/csharp/Base.Server/Base.Server.csproj
  services/csharp/Common/Common.csproj
  services/csharp/Common/Common.nuspec
  services/csharp/Proto/Proto.csproj
Labels: jira/no-ticket, size/XS
