Repository spatialos/online-services, pull requests merged in 2019-09, with the labels that each got.

#84 Update deployment pool docs
  docs/content/configuration-examples/deployment-pool/usage.md
  services/k8s/deployment-pool/deployment.yaml
Labels: jira/no-ticket, size/S

#85 Quick start improvements
  docs/content/get-started/quickstart-3.md
  docs/content/get-started/quickstart-4.md
  docs/content/get-started/quickstart-5.md
  docs/content/get-started/quickstart.md
  services/k8s/config.yaml
  services/k8s/deployment-pool/deployment.yaml
  services/k8s/gateway-internal/deployment.yaml
  services/k8s/gateway/deployment.yaml
  services/k8s/gateway/service.yaml
  services/k8s/party/deployment.yaml
  services/k8s/party/service.yaml
  services/k8s/playfab-auth/deployment.yaml
  services/k8s/playfab-auth/service.yaml
  services/k8s/sample-matcher/deployment.yaml
Labels: jira/no-ticket, size/M

#86 Fix bad git grep command
  docs/content/get-started/quickstart-4.md
Labels: jira/no-ticket, size/XS

#87 Fix incorrect Redis host substitution
  services/k8s/config.yaml
Labels: jira/no-ticket, size/XS

#97 updated python code
  services/python/analytics-pipeline/src/dataflow/common/bigquery_schema.py
  services/python/analytics-pipeline/src/dataflow/common/functions.py
  services/python/analytics-pipeline/src/endpoint/scale_test.py
  services/python/analytics-pipeline/src/function/main.py
  services/python/analytics-pipeline/src/requirements/endpoint.txt
  services/python/analytics-pipeline/src/requirements/function.txt
  services/python/analytics-pipeline/src/requirements/scale-test.txt
Labels: jira/no-ticket, size/M

#89 fix analytics sender
  services/csharp/Common/Analytics/AnalyticsSender.cs
  services/csharp/Common/Analytics/AnalyticsSenderClassWrapper.cs
  services/csharp/Common/Analytics/IAnalyticsSender.cs
  services/csharp/Common/Analytics/NullAnalyticsSender.cs
Labels: jira/no-ticket, size/M

#99 Enable Nunit test reporting in buildkite
  .buildkite/premerge.steps.yaml
  ci/build.sh
  services/csharp/DataModel.Test/DataModel.Test.csproj
  services/csharp/DeploymentPool.Test/DeploymentPool.Test.csproj
  services/csharp/Gateway.Test/Gateway.Test.csproj
  services/csharp/GatewayInternal.Test/GatewayInternal.Test.csproj
  services/csharp/IntegrationTest.Matcher/IntegrationTest.Matcher.csproj
  services/csharp/IntegrationTest/IntegrationTest.csproj
  services/csharp/IntegrationTest/test.ps1
  services/csharp/IntegrationTest/test.sh
  services/csharp/MemoryStore.Test/MemoryStore.Test.csproj
  services/csharp/Party.Test/Party.Test.csproj
Labels: jira/no-ticket, size/M

#100 Replace your_google_project_name with your_google_project_id
  docs/content/get-started/quickstart-3.md
  docs/content/get-started/quickstart-4.md
  services/k8s/deployment-pool/deployment.yaml
  services/k8s/gateway-internal/deployment.yaml
  services/k8s/gateway/deployment.yaml
  services/k8s/party/deployment.yaml
  services/k8s/playfab-auth/deployment.yaml
  services/k8s/sample-matcher/deployment.yaml
Labels: jira/no-ticket, size/M

#96 k8s yaml changes + addition of config file for instrumentation
  services/csharp/Common/Analytics/AnalyticsSender.cs
  services/csharp/Party.Test/JoinPartyShould.cs
  services/csharp/Party.Test/KickOutPlayerShould.cs
  services/k8s/analytics-config.yaml
  services/k8s/analytics-endpoint/deployment.yaml
  services/k8s/analytics-endpoint/service.yaml
  services/k8s/deployment-pool/deployment.yaml
  services/k8s/gateway-internal/deployment.yaml
  services/k8s/gateway/deployment.yaml
  services/k8s/gateway/service.yaml
  services/k8s/party/deployment.yaml
  services/k8s/party/service.yaml
  services/k8s/playfab-auth/deployment.yaml
  services/k8s/playfab-auth/service.yaml
  services/k8s/sample-matcher/deployment.yaml
Labels: jira/no-ticket, size/L

#98 Terraform analytics update
  services/csharp/Party.Test/DeleteInviteShould.cs
  services/csharp/Party.Test/DeletePartyShould.cs
  services/csharp/Party.Test/JoinPartyShould.cs
  services/csharp/Party.Test/KickOutPlayerShould.cs
  services/csharp/Party.Test/LeavePartyShould.cs
  services/terraform/gke.tf
  services/terraform/module-analytics/bigquery.tf
  services/terraform/module-analytics/cloud-function.tf
  services/terraform/module-analytics/logging.tf
  services/terraform/module-analytics/pubsub.tf
  services/terraform/module-analytics/service-accounts-dataflow.tf
Labels: jira/no-ticket, size/M

#101 Read PlayFab secret from literal value rather than a file
  docs/content/get-started/quickstart-4.md
  services/k8s/playfab-auth/deployment.yaml
Labels: jira/no-ticket, size/XS

#90 instrumented deployment pool
  services/csharp/DeploymentPool/DeploymentPool.cs
  services/csharp/DeploymentPool/DeploymentPool.csproj
  services/csharp/DeploymentPool/PlatformInvoker.cs
  services/csharp/DeploymentPool/Program.cs
  services/k8s/deployment-pool/deployment.yaml
Labels: jira/no-ticket, size/M

#102 Instrument playfab auth
  services/csharp/PlayFabAuth/PlayFabAuthImpl.cs
  services/csharp/PlayFabAuth/Program.cs
Labels: jira/no-ticket, size/S

#103 Instrument gateway
  services/csharp/DataModel.Test/EntryDeserializeShould.cs
  services/csharp/DataModel/DataModel.csproj
  services/csharp/DataModel/Entry.cs
  services/csharp/DataModel/Gateway/PartyJoinRequest.cs
  services/csharp/DataModel/Gateway/PlayerJoinRequest.cs
  services/csharp/Gateway.Test/OperationsServiceDeleteOperationShould.cs
  services/csharp/Gateway.Test/OperationsServiceGetOperationShould.cs
  services/csharp/Gateway/GatewayServiceImpl.cs
  services/csharp/Gateway/OperationsServiceImpl.cs
  services/csharp/Gateway/Program.cs
  services/csharp/Proto/generated/Gateway.cs
  services/proto/gateway/gateway.proto
Labels: jira/no-ticket, size/M

#104 Instrument gateway internal
  services/csharp/GatewayInternal.Test/AssignDeploymentsShould.cs
  services/csharp/GatewayInternal.Test/ListWaitingPartiesShould.cs
  services/csharp/GatewayInternal/GatewayInternalServiceImpl.cs
  services/csharp/GatewayInternal/Program.cs
  services/csharp/Proto/generated/GatewayInternal.cs
  services/proto/gateway/gateway_internal.proto
Labels: jira/no-ticket, size/M

#105 Instrument sample matcher
  services/csharp/Party.Test/GetInviteShould.cs
  services/csharp/SampleClient/Program.cs
  services/csharp/SampleMatcher/Matcher.cs
  services/csharp/SampleMatcher/Program.cs
  services/csharp/SampleMatcher/SampleMatcher.csproj
Labels: jira/no-ticket, size/M

#107 Instrument party
  services/csharp/Party.Test/CreateInviteShould.cs
  services/csharp/Party.Test/CreatePartyShould.cs
  services/csharp/Party.Test/DeleteInviteShould.cs
  services/csharp/Party.Test/DeletePartyShould.cs
  services/csharp/Party.Test/JoinPartyShould.cs
  services/csharp/Party.Test/KickOutPlayerShould.cs
  services/csharp/Party.Test/LeavePartyShould.cs
  services/csharp/Party.Test/UpdatePartyShould.cs
  services/csharp/Party/InviteServiceImpl.cs
  services/csharp/Party/PartyServiceImpl.cs
  services/csharp/Proto/generated/PartyGrpc.cs
  services/proto/party/party.proto
Labels: jira/no-ticket, size/M

#106 Fix party tests
  services/csharp/Common.Test/AnalyticsShould.cs
  services/csharp/Common.Test/Common.Test.csproj
  services/csharp/Party.Test/AnalyticsConstants.cs
  services/csharp/Party.Test/CreateInviteShould.cs
  services/csharp/Party.Test/CreatePartyShould.cs
  services/csharp/Party.Test/DeleteInviteShould.cs
  services/csharp/Party.Test/DeletePartyShould.cs
  services/csharp/Party.Test/JoinPartyShould.cs
  services/csharp/Party.Test/KickOutPlayerShould.cs
  services/csharp/Party.Test/LeavePartyShould.cs
  services/csharp/Party.Test/UpdatePartyShould.cs
  services/csharp/Party/PartyServiceImpl.cs
Labels: jira/no-ticket, size/M

#108 explicitly set the default match tag used by matcher
  services/k8s/sample-matcher/deployment.yaml
Labels: jira/no-ticket, size/XS

#109 added enablement of cloud function api to terraform
  services/terraform/services.tf
Labels: jira/no-ticket, size/XS

#110 upgraded ESP container version in docker compose
  services/docker/docker_compose_local_analytics.yml
  services/docker/docker_compose_local_services.yml
Labels: jira/no-ticket, size/XS

#88 Docs deployment pool fixes
  docs/content/configuration-examples/deployment-pool/usage.md
Labels: jira/no-ticket, size/XS

#111 Upgrade gRPC packages across solution to 1.22.1
  services/csharp/Base.Server/Base.Server.csproj
  services/csharp/Common/Common.csproj
  services/csharp/Common/Common.nuspec
  services/csharp/Proto/Proto.csproj
  services/csharp/Proto/generated/GatewayGrpc.cs
  services/csharp/Proto/generated/GatewayInternal.cs
  services/csharp/Proto/generated/GatewayInternalGrpc.cs
  services/csharp/Proto/generated/Invite.cs
  services/csharp/Proto/generated/InviteGrpc.cs
  services/csharp/Proto/generated/Party.cs
  services/csharp/Proto/generated/PartyGrpc.cs
  services/csharp/Proto/generated/PlayfabGrpc.cs
Labels: jira/no-ticket, size/XS
